name: atm-env3
channels:
  - defaults
dependencies:
  - attrs=19.1.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - bzip2=1.0.6
  - ca-certificates=2019.8.28
  - cairo=1.14.12
  - certifi=2019.9.11
  - curl=7.64.1
  - cycler=0.10.0
  - dbus=1.13.6
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - freexl=1.0.5
  - fribidi=1.0.5
  - gdal=2.3.3
  - geos=3.7.1
  - gettext=0.19.8.1
  - giflib=5.1.4
  - glib=2.56.2
  - graphite2=1.3.13
  - graphviz=2.40.1
  - harfbuzz=1.8.8
  - hdf4=4.2.13
  - hdf5=1.10.4
  - icu=58.2
  - intel-openmp=2019.3
  - ipykernel=5.1.1
  - ipython=7.5.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.4.2
  - jedi=0.13.3
  - jinja2=2.10.1
  - jpeg=9b
  - json-c=0.13.1
  - jsonschema=3.0.1
  - jupyter=1.0.0
  - jupyter_client=5.2.4
  - jupyter_console=6.0.0
  - jupyter_core=4.4.0
  - kealib=1.4.7
  - kiwisolver=1.1.0
  - krb5=1.16.1
  - libboost=1.67.0
  - libcurl=7.64.1
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libdap4=3.19.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgdal=2.3.3
  - libgfortran=3.0.1
  - libiconv=1.15
  - libkml=1.3.0
  - libnetcdf=4.6.1
  - libpng=1.6.37
  - libpq=11.2
  - libsodium=1.0.16
  - libspatialite=4.3.0a
  - libssh2=1.8.2
  - libtiff=4.0.10
  - libxml2=2.9.9
  - llvmlite=0.28.0
  - markupsafe=1.1.1
  - matplotlib=3.1.0
  - mistune=0.8.4
  - mkl=2019.3
  - mkl_fft=1.0.12
  - mkl_random=1.0.2
  - nbconvert=5.5.0
  - nbformat=4.4.0
  - ncurses=6.1
  - notebook=5.7.8
  - numba=0.43.1
  - numpy=1.16.4
  - numpy-base=1.16.4
  - openjpeg=2.3.0
  - openssl=1.1.1d
  - pandas=0.24.2
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - pango=1.42.4
  - parso=0.4.0
  - pcre=8.43
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pip=19.1.1
  - pixman=0.38.0
  - poppler=0.65.0
  - poppler-data=0.4.9
  - proj4=5.2.0
  - prometheus_client=0.6.0
  - prompt_toolkit=2.0.9
  - ptyprocess=0.6.0
  - pydot=1.4.1
  - pygments=2.4.0
  - pyparsing=2.4.0
  - pyqt=5.9.2
  - pyrsistent=0.14.11
  - python=3.7.3
  - python-dateutil=2.8.0
  - pytz=2019.1
  - pyyaml=5.1
  - pyzmq=18.0.0
  - qt=5.9.7
  - qtconsole=4.5.1
  - readline=7.0
  - scikit-learn=0.20.3
  - scipy=1.2.1
  - send2trash=1.5.0
  - setuptools=41.0.1
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.28.0
  - tbb=2019.4
  - terminado=0.8.2
  - testpath=0.4.2
  - tk=8.6.8
  - tornado=6.0.2
  - traitlets=4.3.2
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.4
  - widgetsnbextension=3.4.2
  - xerces-c=3.2.2
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.3.1
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - chardet==3.0.4
    - decorator==4.4.0
    - idna==2.8
    - imageio==2.5.0
    - imageio-ffmpeg==0.3.0
    - moviepy==1.0.0
    - pillow==6.0.0
    - requests==2.22.0
    - tqdm==4.32.1
    - urllib3==1.25.3
